name: cat_api
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.1.0
  cached_network_image: ^3.3.1 #Navigation of routes
  shimmer: ^3.0.0
  go_router: ^13.2.0
  flutter_dotenv: ^5.1.0
  rive: ^0.12.4
  google_fonts: ^6.2.1
  freezed: ^2.4.7

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/rive/
    - assets/images/
